markdown: GFM
title: Andreas Postel # your name (or website title) here
logo: "/images/fireworks.gif?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <h2>Happy Birthday!</h2>
  <br><br>
  Have fun!
  <br><br>
  
theme: jekyll-theme-minimal
